---
- name: "prem : provision : Generate instructor inventory {{config_libre.directory.conf}}/inventory/instructor.yml"
  template:
    src: "templates/inventory-instructor.j2"
    dest: "{{config_libre.directory.conf}}/inventory/instructor.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : provision : Generate students inventory {{config_libre.directory.conf}}/inventory/students.yml"
  template:
    src: "templates/inventory-students.j2"
    dest: "{{config_libre.directory.conf}}/inventory/students.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : provision : Copy ssh private key {{ libre_infra_prem_ssh_private_key_file }} to {{config_libre.directory.conf}}/infra_rsa"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-prem_rsa"
    dest: "{{config_libre.directory.conf}}/infra-prem_rsa"
    mode: 0644
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : provision : Copy ssh public key {{ libre_infra_prem_ssh_public_key_file }} to {{config_libre.directory.conf}}/infra_rsa.pub"
  copy:
    src: "{{r_libre_userconfig_dir}}/infra-prem_rsa.pub"
    dest: "{{config_libre.directory.conf}}/infra-prem_rsa.pub"
    mode: 0644
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : provision : TODO !!!"
  debug:
    msg: "prem : provision : TODO !!!"
