## LIBRE role default variables

r_do: "{{ do | string }}"

r_libre_uninstall_deep: "{{ libre_uninstall_deep | bool }}"
r_libre_force_upgrade: "{{ libre_force_upgrade | bool }}"

r_libre_dest_lib: "{{ libre_dest_lib }}"
r_libre_dest_bin: "{{ libre_dest_bin }}"
r_libre_dest_ansible: "{{ libre_dest_ansible }}"

r_libre_config_file_hw: "{{ libre_config_file_hw | string }}"

r_libre_user: "{{ libre_user | string }}"
r_libre_group: "{{ libre_group | string }}"
r_libre_userconfig_dir: "{{ libre_userconfig_dir | string }}"
r_libre_myconfile_libre: "{{ libre_myconfile_libre | string }}"
r_libre_myconfile_session: "{{ libre_myconfile_session | string }}"
r_libre_myconfile_infra: "{{ libre_myconfile_infra | string }}"
r_libre_myconfile_repository: "{{ libre_myconfile_repository | string }}"
r_libre_dir: "{{ training_dir | string }}"
r_libre_dir_course: "{{ training_dir_course | string }}"
r_libre_dir_conf: "{{ training_dir_conf | string }}"
r_libre_dir_collect: "{{ training_dir_collect | string }}"
r_libre_tmp: "{{ libre_tmp | string }}"
r_libre_tmpfile: "{{ libre_tmpfile | string }}"

r_libre_libre_userconf_default:
  application:
    type: "{{ libre_type | string }}"
    version: "{{ libre_version | string }}"
    verbose: "{{ libre_verbose | bool }}"
    debug: "{{ libre_debug | bool }}"
    source:
      repo: "{{ libre_source_url }}"
      branch: "{{ libre_source_branch }}"
      base: "{{ libre_source_base }}"
      tmp: "{{ libre_source_tmp }}"
  directory:
    base: "{{ r_libre_dir }}"
    conf: "{{ r_libre_dir_conf }}"
    course: "{{ r_libre_dir_course }}"
    collect: "{{ r_libre_dir_collect }}"
r_libre_session_userconf_default:
  type: "{{ libre_session_type | string }}"
  gapi: "{{ libre_session_gapi | string }}"
r_libre_infra_userconf_default:
  default: "{{ libre_infra_default | string }}"
  self:
    type: "self"
    image: "{{ infra_self_image | string }}"
    network:
      dns: "{{ infra_self_dns_zone | string }}"
      associated_ip: "{{ infra_associated_ip | string }}"
  prem:
    type: "prem"
    network:
      dns: "{{ infra_prem_dns_zone | string }}"
    ssh:
      privateKey_file: "{{ infra_prem_ssh_private_key_file | string }}"
      user: "{{ infra_prem_ssh_user | string }}"
  aws:
    type: "aws"
    auth:
      access_key: "{{ infra_aws_access_key }}"
      secret_key: "{{ infra_aws_secret_key }}"
    route53:
      zone: "{{ infra_aws_route53_dns_zone | string }}"
      domain: "{{ infra_aws_public_dns_zone | string }}"
    ec2:
      region: "{{ infra_aws_region | string }}"
      type: "{{ infra_aws_instance_type | string }}"
      image: "{{ infra_aws_image | string }}"
    ssh:
      keyname: "{{ infra_aws_key_name | string }}"
      privateKey_file: "{{ infra_aws_ssh_private_key_file | string }}"
      user: "{{ infra_aws_ssh_user | string }}"
r_libre_repository_userconf_default:
  url: "{{ repository_url | string }}"
  branch: "{{ repository_branch | string }}"
  base: "{{ repository_base | string }}"
  local: "{{ repository_local | string }}"

r_libre_minhw:
  architecure: "{{ libre_minhw_architecure | string }}"
  cpu:
    physical: "{{ libre_minhw_cpu_physical | int }}"
    cores: "{{ libre_minhw_cpu_cores | int }}"
    vcpus: "{{ libre_minhw_cpu_vcpus | int }}"
  memory:
    total: "{{ libre_minhw_memory_total | int }}"
    free: "{{ libre_minhw_memory_free | int }}"
  storage:
    percent: "{{ libre_minhw_storage_percent | int }}"
    capacity: "{{ libre_minhw_storage_capacity | int }}"

r_libre_files_library:
  - "libre-chapter"
  - "libre-chapter.txt"
  - "libre-infra"
  - "libre-infra.txt"
  - "libre-core"
  - "libre-instructor"
  - "libre-instructor.txt"
  - "libre-repository"
  - "libre-repository.txt"
  - "libre-lab"
  - "libre-lab.txt"
  - "libre-session"
  - "libre-session.txt"
  - "libre-student"
  - "libre-student.txt"

r_libre_files_binary_all:
  - "libre-chapter"
  - "libre-infra"
  - "libre-instructor"
  - "libre-repository"
  - "libre-lab"
  - "libre-session"
  - "libre-student"

r_libre_files_binary_instructor:
  - "libre-chapter"
  - "libre-infra"
  - "libre-instructor"
  - "libre-repository"
  - "libre-lab"
  - "libre-session"

r_libre_files_binary_student:
  - "libre-lab"
  - "libre-student"
