---
# Stop pre-tasks
- name: "stop : Stop course {{ libre_course.id }}"
  include_tasks: "{{ r_session_dir_course }}/{{ r_session_dir_course_playbooks}}/stop.yml"
  when: r_session_dir_course_playbooks_details.stat.exists
- name: "stop : Stop LIBRE-instructor web application for session {{ libre_session.id }}"
  docker_container:
    name: "libre-instructor-{{ libre_session.id }}"
    state: stopped
  become: yes

# Stop tasks
- name: "stop : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_libre_tmpfile) }}"
  delegate_to: localhost
- name: "stop : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
  template:
    src: libre_report-stop.j2
    dest: "{{ r_libre_tmp }}/{{ r_libre_tmpfile }}"
    mode: 0664
  delegate_to: localhost
- name: "stop : Log stop action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Session is stopped"
    log_component: session
    log_action: stop
