---
- name: "load_directory : Get {{ config_libre.directory.base }} directory details"
  stat:
    path: "{{ config_libre.directory.base }}"
  register: r_libre_dir_details
- name: "load_directory : Get {{ config_libre.directory.course }} directory details"
  stat:
    path: "{{ config_libre.directory.course }}"
  register: r_libre_dir_course_details
- name: "load_directory : Get {{ config_libre.directory.collect }} directory details"
  stat:
    path: "{{ config_libre.directory.collect }}"
  register: r_libre_dir_collect_details
- name: "load_directory : Get {{ config_libre.directory.conf }} directory details"
  stat:
    path: "{{ config_libre.directory.conf }}"
  register: r_libre_dir_conf_details
- name: "load_directory : Get configuration directory {{ r_libre_userconfig_dir }}"
  stat:
    path: "{{ r_libre_userconfig_dir }}"
  register: r_libre_userconfig_dir_details
  become: no
