app:
  container_name: "libre-instructor-dev"
  build: ./libre-instructor
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  ports:
    - "1901:8080"
  volumes:
    - "./libre-instructor/sxapi.yml:/conf/sxapi.yml:z"
    - "./libre-instructor/static:/usr/src/app/static:z"
    - "./course-dev/conf:/usr/src/app/config:z"
    - "./course-dev/course:/usr/src/app/course:z"
    - "./course-dev/collect:/usr/src/app/data:z"

