---
- name: "install_services : Ensure dependencies packages are installed"
  yum:
    name:
    - git
    - ansible
    - docker
    - bind-utils
    - rng-tools
    - bash-completion
    #- ipa-server # TODO: Move this prerequisite to the infra/prem role

- name: "install_services : Force upgrading pip packages manager"
  command: "pip install --upgrade pip"

- name: "install_services : Install and force upgrade pip packages"
  pip:
    name: "{{ pipname }}"
    state: forcereinstall
    extra_args: --upgrade --user
  loop:
    - pip
    - Jinja2
    - docker
  loop_control:
    loop_var: pipname

#- name: "install_services : Ensure rng service is running"
#  systemd:
#    name: rngd
#    state: started

- name: "install_services : Ensure docker service is running"
  systemd:
    name: docker
    state: started
