app:
  container_name: "libre-instructor"
  build: .
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  ports:
    - "1900:8080"
  volumes:
    - "./sxapi.yml:/conf/sxapi.yml:z"
    - "./static:/usr/src/app/static:z"
    - "/usr/share/libre/conf:/usr/src/app/config:z"
    - "/usr/share/libre/course:/usr/src/app/course:z"
    - "/usr/share/libre/collect:/libre-collect:z"

