## LIBRE infra_aws role tasks
---
- name: "Set libre_infra if infra_type is set"
  set_fact:
    libre_infra_type: "{{ infra_type }}"
  when: infra_type|string in ['self','aws','prem']
- name: "Action {{ do | default('load') | string }} in infrastructure role is supported"
  assert:
    msg: "Action {{ do | default('load') | string }} in infrastructure role is not supported"
    that: do|default('load')|string in ['load','config','status','provision','provision-post','deprovision']
- name: "{{ do | default('load') | string }} infrastructure environement"
  include_tasks: "{{ do | default('load') | string }}.yml"
  vars:
  when: do|default('load')|string in ['load','config','status','provision','provision-post','deprovision']
