---
- name: "Deprovision classroom infrastructure on instructor"
  hosts: 'instructor'
  gather_facts: true

  roles:
    - { role: infra, do: load, infra_type: self }
    - { role: infra, do: deprovision, infra_type: self, become: yes }
